<a href="https://colab.research.google.com/github/Mukeshbabu6567/KIET_Class_01/blob/main/kiet_perceptron_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
np.random.randn(3)

array([-1.13753672, -1.19693113,  0.21626558])

In [ ]:
1e-4

0.0001

In [ ]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    self.eta = eta
    self.epochs = epochs

  def act(self, inputs, weights):
    z = np.dot(inputs, weights)
    y_hat = np.where(z >= 0, 1, 0)
    return y_hat

  def fit(self, x, y):
    self.x = x
    self.y = y
    X_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]

    for epoch in range(self.epochs):
      y_hat = self.act(X_with_bias, self.weights)
      self.error = self.y - y_hat
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)

  def predict(self, x):
    X_with_bias = np.c_[x, -np.ones((len(x), 1))]
    pred = self.act(X_with_bias, self.weights)
    return pred

In [ ]:
-np.ones((5, 1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [ ]:
obj = Perceptron(0.1, 10)

In [ ]:
obj.eta

0.1

In [ ]:
obj.epochs

10

In [ ]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1],
}

df = pd.DataFrame(AND)

df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [ ]:
ETA = 0.1
EPOCHS = 10

model = Perceptron(eta=ETA, epochs=EPOCHS)

In [ ]:
def prepare_data(df):
  x  = df.drop("y", axis=1)
  y = df["y"]
  return x, y

In [ ]:
x, y = prepare_data(df)

In [ ]:
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [ ]:
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [ ]:
model.fit(x, y)

In [ ]:
model.weights

array([0.19980258, 0.10002051, 0.20000308])

In [ ]:
model.predict(x)

array([0, 0, 0, 1])

In [ ]:
model.predict([[0,0]])

array([0])

In [ ]:
model.predict([[1,1]])

array([1])